// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SalesContext))]
    partial class SalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.Entities.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Klucz główny tabeli z informacjami o mieszkaniach")
                        .UseIdentityColumn();

                    b.Property<double>("Area")
                        .HasColumnType("float")
                        .HasComment("Powierzchnia mieszkania (w metrach kwadratowych)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Opis ogłoszenia");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasComment("Piętro");

                    b.Property<string>("FormOfOwnership")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Forma własności");

                    b.Property<string>("Heating")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Rodzaj ogrzewania");

                    b.Property<string>("KindOfBalcony")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Typ balkonu (jeśli brak - wartość pusta)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int")
                        .HasComment("Liczba pokoi");

                    b.Property<string>("ParkingSpace")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Parking (jeśli brak - wartość pusta)");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasComment("Cena (za metr kwadratowy)");

                    b.Property<string>("StateOfCompletion")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Status wykończenia mieszkania");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Tytuł ogłoszenia");

                    b.HasKey("Id");

                    b.ToTable("Flats");
                });
#pragma warning restore 612, 618
        }
    }
}
